encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new_page, name="new"),
    path("random/", views.random_page, name="random"),
    path("<str:name>/", views.g_entry, name="entry"),
    path("<str:name>/edit/", views.edit_page, name="edit"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

class NewPageForm(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={
        'class': 'form-control custom-textinput',
        'placeholder': 'Enter page title...'
    }))
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={
        'class': 'form-control custom-textarea' ,
        'placeholder': 'Enter the Content (in Markdown)...'
    }))

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import NewPageForm
from . import util
import markdown2
import random

def index(request):
    """
    renders the index (home page)
    """
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def g_entry(request, name):
    """
    function to render a wiki page based on request 
    if GET request, match the query and show results
    else show entry that is clicked on
    """
    
    if 'q' in request.GET:
        query = request.GET.get('q').strip()    
        if query:
            entries = util.list_entries()
            results = [entry for entry in entries if query.lower() in entry.lower()]  
            if (len(results) == 1) and (results[0].lower() == query.lower()):
                return redirect(reverse('wiki:entry', kwargs={'name':results[0]}))
            else:
                return render(request, "encyclopedia/search_results.html", {
                    "title":"Results",
                    "entries":results
                })
        else:
            return render(request, "encyclopedia/search_results.html", {
                "title":"404",
                "entries":results
            })


    entry = util.get_entry(name)

    if entry is None:
        return render(request, "encyclopedia/404.html")
    
    html_content = markdown2.markdown(entry)

    return render(request, "encyclopedia/entry.html", {
        "title": name,
        "content": html_content,
    })

def new_page(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)

        if form.is_valid():
            title=form.cleaned_data['title'].strip()
            content=form.cleaned_data['content'].strip()

            if util.get_entry(title) is not None:
                return render(request, "encyclopedia/new_page.html", {
                    "title": title,
                    "form": form,
                    "error": "An entry with this title already exists."
                })

            util.save_entry(title, content)
            return redirect(reverse('wiki:entry', kwargs={'name':title}))
    else:
        form = NewPageForm()
    return render(request, "encyclopedia/new_page.html", {
        "form":form
    })

def edit_page(request, name):
    entry = util.get_entry(name)
    if entry is None:
        return render(request, "encyclopedia/404.html")
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title'].strip()
            content = form.cleaned_data['content'].strip()
            util.save_entry(title, content)
            return redirect(reverse('wiki:entry', kwargs={'name':name}))
    else:
        form = NewPageForm(initial={'title':name, 'content': entry})
        return render(request, "encyclopedia/edit_page.html", {
            "title": name,
            "form": form,
        })

def random_page(request):
    entries = util.list_entries()
    random_entry = random.choice(entries)
    return g_entry(request, random_entry)

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}

    <h1 style="padding-left: 1%;">Edit Page Entry</h1>
    <div class="custom-form">
        <form action="{% url 'wiki:edit' title %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Save Page</button>
        </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    {{content|safe}}
    <a href="{% url 'wiki:edit' title %}" class="btn btn-secondary">Edit Page</a>
{% endblock %}  

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for e in entries %}
        <!-- entries is a variable passed along when rendering index.html -->
            <li><a href="{% url 'wiki:entry' e %}">{{ e }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki🌐</h2>
                <form action="{% url 'wiki:entry' name='foo' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia" value="{{ request.GET.q }}">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New Page
{% endblock %}

{% block body %}

    {% if error %}
        <div class="alert alert-danger">{{ error }} <a href="{% url 'wiki:edit' title %}" style="color: #6c747e;">Click here</a> to edit it.</div>
    {% endif %}

    <h1 style="padding-left: 1%;">New Page Entry</h1>
    <div class="custom-form">
        <form action="{% url 'wiki:new' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary">Save Page</button>
        </form>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <ul>
    {% for entry in entries %}
        <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
    {% empty %}
        <li>No such matches.</li>
    {% endfor %}
    </ul>
{% endblock %}